### PR TITLE
fix(sort-or-choose&choose-house): improve the layout

### LINKED ISSUE #96: Improve choose-house page and sort-or-choose page
Increase the size of elements to fulfill the page.

### PR DESCRIPTION
**Pull request by litianqing2887**
### Tracking Info

Resolves #96

Make sure your branch name conforms to: `<feature/<username>/<3-4 word description separated by dashes>`. Otherwise, please rename your branch and create a new PR.

### Changes

What changes did you make?

- Change the size of elements of sort-or-choose page and choose-house page

### Testing (ignore if on ui/ux team)

How did you confirm your changes worked? 

- Reviewing the updated web page

### Confirmation of Change (ignore if on ui/ux team)

Upload a screenshot or video (preferable a video), if possible. Otherwise, please provide instructions on how to see the change.

image
image
image
image

### CODE REVIEW

File: source/components/ChooseHouseSection.js [hunk 1]
```diff
@@ -38,7 +38,7 @@ class ChooseHouseSection extends HTMLElement {
         .option {
           order-radius: 0.5rem;
           padding: 1.5rem;
-          max-width: 12rem;
+          max-width: 16rem;
```
Comment (Kiyo5hi) [inline source/components/ChooseHouseSection.js:41]: did you test this? will this overflow on tiny screens?

Comment (Kiyo5hi) [inline source/components/ChooseHouseSection.js:41]: did you test this? will this overflow on tiny screens?

**Review by Kiyo5hi — CHANGES_REQUESTED** [review]

File: source/components/ChooseHouseSection.js (hunk 1 above)
Comment (litianqing2887) [reply source/components/ChooseHouseSection.js:41]: By checking the mobile emulation in chrome. It fits commonly used mobile devices.

**Review by Kiyo5hi — APPROVED** [review]
